---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  set -a
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: ubi8/ubi-init
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    command: "/usr/sbin/init"
provisioner:
  name: ansible
verifier:
  name: ansible
