---
- hosts: all
  become: true
  gather_facts: true
  tasks:
  - name: remove_NGINX
    yum:
      name: nginx
      state: removed 
  - name: intsall_HTTPd
    yum:
      name: httpd
      state: present
    notify:
    - enable_HTTPd
  - name: Copy a web page
      copy:
        content: |
          <html>
          <head><title>Test OK!</title></head>
          <body>Test OK!</body>
          </html>
        dest: "/var/www/html/index.html"
        mode: 0664
      notify:
      - enable_HTTPd
  handlers:
  - name: enable_HTTPd
    systemd:
      name: httpd
      enabled: yes
      state: started
