name : playbook-test

on:
  push:
    branches:
      - main

jobs:
  test:
  name: Molecule
  runs-on: ubuntu-22.04

  steps:
    - name: checkout-codebase
      uses: actions/checkout@v2

    - name: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: install-dependencies
      run: pip3 install molecule[docker] yamllint ansible-lint

    - name: run-tests
      run: molecule test
      env:
        PY_COLOURS: '1'
        ANSIBLE_FORCE_COLOR: '1' 